### ISSUE TITLE
how can i run this code

### ISSUE THREAD

**Issue by dongspam0209** [GangSuUGA/Traffic-Signal-Control-#4]
I think there are some differences in your utils.py code with utils.py in reference, how can i run this code i want to know the requirements of this source code.

**Comment by dongspam0209** [comment]
oh I figured it out, but after the training, I want to test my trained model. How can i do that?
![그림1](https://github.com/GangSuUGA/StageLight/assets/98256216/d703501f-8641-4c6d-89b0-90f638cae2d0)

**Comment by dongspam0209** [comment]
also can you tell me what this variables for? This picture is small part of training class
![image](https://github.com/GangSuUGA/StageLight/assets/98256216/381578d8-1b60-4d29-8c8b-55f94491811a)

and also I want to know why there are two inputs of actions in Critic models code
![image](https://github.com/GangSuUGA/StageLight/assets/98256216/cde10c6c-9ab4-482a-8b05-0efc841a3fe7)

Apologies for the unclear code writing.
I believe a = current_phase, b = current_duration, c = next_phase, d = next_duration. 
If you don't mind, printing those variables would be more clear.

**Comment by GangSuUGA** [comment]
> oh I figured it out, but after the training, I want to test my trained model. How can i do that? ![그림1](https://private-user-images.githubusercontent.com/98256216/296864172-d703501f-8641-4c6d-89b0-90f638cae2d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjI3NTUsIm5iZiI6MTcwNTU2MjQ1NSwicGF0aCI6Ii85ODI1NjIxNi8yOTY4NjQxNzItZDcwMzUwMWYtODY0MS00YzZkLTg5YjAtOTBmNjM4Y2FlMmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA3MjA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NzQ4MDBmZmNiMDI1NzgxNzcwOTQwYzFiYzkyYzQyNDEwODM3ZjNmYWE5MmUxZmVkOWZlNWY4YTY1YTYyODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r8uRbNd2V9dDEXe7FI4gWrcvTHnLNBHiJYguhjI6lCw)

Thanks for your issues!
Uncomment this line of code：# Model._load_my_model(model_path)
Then set the parameter: model_to_test = 1   # load model
From your picture, I believe model_to_test should be set to 2. 

And don't forget the epsilon (=0 when test) and comment the code about Training.run().

**Comment by dongspam0209** [comment]
![image](https://github.com/GangSuUGA/StageLight/assets/98256216/9190c45b-f71e-4452-ae36-e79b0a436c59)
Thanks! I think the model loaded successfully, If I want to see the test result with sumo simulation, should I run the sumocfg file?
